export enum LabTestActions {
  /**
   * fetch labTests
   */

  LAB_TESTS_FR_FETCH = "@@labtests/LAB_TESTS_FR_FETCH",
  LAB_TESTS_FR_FETCH_ERROR = "@@labtests/LAB_TESTS_FR_FETCH_ERROR",
  LAB_TESTS_FR_FETCH_SUCCESS = "@@labtests/LAB_TESTS_FR_FETCH_SICCESS",

  /**
   * search Labtests
   */

  LAB_TESTS_FR_SEARCH = "@@labtests/LAB_TESTS_FR_SEARCH",
  LAB_TESTS_FR_SEARCH_ERROR = "@@labtests/LAB_TESTS_FR_SEARCH_ERROR",
  LAB_TESTS_FR_SEARCH_SUCCESS = "@@labtests/LAB_TESTS_FR_SEARCH_SUCCESS",

  /**
   * fetch all labtests 
   */
  LAB_TESTS_EN_FETCH = "@@labtests/LAB_TESTS_EN_FETCH",
  LAB_TESTS_EN_FETCH_ERROR = "@@labtests/LAB_TESTS_EN_FETCH_ERROR",
  LAB_TESTS_EN_FETCH_SUCCESS = "@@labtests/LAB_TESTS_EN_FETCH_SUCCESS",

  /**
   * fetch Test details En
   */
  LAB_TESTS_EN_FETCH_DETAILS = "@@labtests/LAB_TESTS_EN_FETCH_DETAILS",
  LAB_TESTS_EN_FETCH_DETAILS_ERROR = "@@labtests/LAB_TESTS_EN_FETCH_DETAILS_ERROR",
  LAB_TESTS_EN_FETCH_DETAILS_SUCCESS = "@@labtests/LAB_TESTS_EN_FETCH_DETAILS_SUCCESS",

  /**
   * fetch Test details Fr
   */
  LAB_TESTS_FR_FETCH_DETAILS = "@@labtests/LAB_TESTS_FR_FETCH_DETAILS",
  LAB_TESTS_FR_FETCH_DETAILS_ERROR = "@@labtests/LAB_TESTS_FR_FETCH_DETAILS_ERROR",
  LAB_TESTS_FR_FETCH_DETAILS_SUCCESS = "@@labtests/LAB_TESTS_FR_FETCH_DETAILS_SUCCESS",

  /**
   * update test details
   */
  LAB_TEST_DETAILS_UPDATE = "@@labtests/LAB_TEST_DETAILS_UPDATE",
  LAB_TEST_DETAILS_UPDATE_ERROR = "@@labtests/LAB_TEST_DETAILS_UPDATE_ERROR",
  LAB_TEST_DETAILS_UPDATE_SUCCESS = "@@labtests/LAB_TEST_DETAILS_UPDATE_SUCCESS",

  /**
   * filter all lab test by english name
   */
  LAB_TESTS_FILTER_BY_EN_NAME = "@@labtests/LAB_TESTS_FILTER_BY_EN_NAME",
  LAB_TESTS_FILTER_BY_EN_NAME_ERROR = "@@labtests/LAB_TESTS_FILTER_BY_EN_NAME_ERROR",
  LAB_TESTS_FILTER_BY_EN_NAME_SUCCESS = "@@labtests/LAB_TESTS_FILTER_BY_EN_NAME_SUCCESS",
}
